// modules/shared/rbac/registry.js
// FEATURE_REGISTRY + RBAC_ROLES — 1-op-1 kopie van admin.html:959-1285.
// Exposes window.KV_RBAC = { FEATURE_REGISTRY, RBAC_ROLES } zodat instellingen-v2
// dezelfde matrix kan renderen zonder admin.html te importeren. Bij wijziging:
// sync deze constanten met admin.html (eenmalig — TODO: verplaatsen naar één bron).
(function(){
const FEATURE_REGISTRY = [
  { moduleKey:'dashboard', moduleLabel:'Dashboard', moduleIcon:'ti-dashboard', features:[
    { key:'dashboard.module.access', label:'Module zichtbaar' },
    { key:'dashboard.sales.view', label:'Sales-dashboard zichtbaar' },
  ]},
  { moduleKey:'email', moduleLabel:'E-mail', moduleIcon:'ti-mail', features:[
    { key:'email.module.access', label:'Module zichtbaar' },
    { key:'email.tab.tebeantwoorden', label:'Tab: Te beantwoorden' },
    { key:'email.tab.sales', label:'Tab: Sales' },
    { key:'email.tab.klanten', label:'Tab: Klanten' },
    { key:'email.tab.finance', label:'Tab: Finance' },
    { key:'email.tab.reclame', label:'Tab: Reclame' },
    { key:'email.tab.overig', label:'Tab: Overig' },
    { key:'email.tab.alle', label:'Tab: Alle mails' },
    { key:'email.tab.verzonden', label:'Tab: Verzonden' },
    { key:'email.reply.send', label:'Reply versturen' },
    { key:'email.ai.generate', label:'AI antwoord genereren' },
    { key:'email.forward.send', label:'Doorsturen' },
    { key:'email.move_train.run', label:'Verplaats & Train' },
    { key:'email.bulk.train', label:'Bulk Train Agent' },
    { key:'email.actie.toggle', label:'Actie vereist toggle' },
    { key:'email.factuur.print', label:'Factuur afdrukken' },
    { key:'email.markread.toggle', label:'Markeer gelezen/ongelezen' },
    { key:'email.kennisbank.add', label:'Toevoegen aan Kennisbank' },
    { key:'email.taak.create', label:'Taak aanmaken' },
    { key:'email.reclassify.run', label:'Reclassify knop' },
    { key:'email.heranalyseer.run', label:'Heranalyseer knop' },
    { key:'email.leerrapport.view', label:'Leerrapport bekijken' },
    { key:'email.training.toggle', label:'Training toggle' },
    { key:'email.signature.edit', label:'Handtekening bewerken' },
  ]},
  { moduleKey:'taken', moduleLabel:'Takenbeheer', moduleIcon:'ti-checklist', features:[
    { key:'taken.module.access', label:'Module zichtbaar' },
    { key:'taken.task.create', label:'Taak aanmaken' },
    { key:'taken.task.edit', label:'Taak bewerken' },
    { key:'taken.task.delete', label:'Taak verwijderen' },
    { key:'taken.task.status_change', label:'Status wijzigen' },
  ]},
  { moduleKey:'kennisbank', moduleLabel:'Kennisbank', moduleIcon:'ti-book-2', features:[
    { key:'kennisbank.module.access', label:'Module zichtbaar' },
    { key:'kennisbank.item.create', label:'Item aanmaken' },
    { key:'kennisbank.item.edit', label:'Item bewerken' },
    { key:'kennisbank.item.delete', label:'Item verwijderen' },
    { key:'kennisbank.profile.edit', label:'Bedrijfsprofiel bewerken (gevoelig)' },
    { key:'kennisbank.tag.manage', label:'Tags beheren' },
    { key:'kennisbank.faq.add', label:'FAQ toevoegen (legacy)' },
    { key:'kennisbank.material.upload', label:'Materiaal uploaden' },
    { key:'kennisbank.bots.activate', label:'Activeren voor AI (gevoelig)' },
  ]},
  { moduleKey:'agents', moduleLabel:'AI Agents', moduleIcon:'ti-robot', features:[
    { key:'agents.module.access', label:'Module zichtbaar' },
    { key:'agents.view.overview', label:'Overview zien' },
    { key:'agents.view.chat', label:'Chat zien' },
    { key:'agents.chat.use', label:'Chat gebruiken' },
    { key:'agents.report.generate', label:'Rapport genereren' },
    { key:'agents.session.new', label:'Nieuwe sessie starten' },
    { key:'agents.train.rule', label:'Train mij / teach-rule' },
    { key:'agents.example.mark_good', label:'Voorbeeld markeren' },
    { key:'agents.approval.act', label:'Approve/Reject acties' },
  ]},
  { moduleKey:'meetings', moduleLabel:'Vergaderruimte', moduleIcon:'ti-users', features:[
    { key:'meetings.module.access', label:'Module zichtbaar' },
    { key:'meetings.tab.history', label:'Tab: Geschiedenis' },
    { key:'meetings.tab.tasks', label:'Tab: Taken' },
    { key:'meetings.tab.standups', label:'Tab: Standups' },
    { key:'meetings.tab.decisions', label:'Tab: Beslissingen' },
    { key:'meetings.meeting.start', label:'Vergadering starten' },
    { key:'meetings.standup.start', label:'Standup starten' },
    { key:'meetings.meeting.end', label:'Vergadering beeindigen' },
    { key:'meetings.meeting.approve', label:'Vergadering goedkeuren' },
    { key:'meetings.tasks.confirm_create', label:'Taken bevestigen aanmaken' },
    { key:'meetings.input.add', label:'Input toevoegen' },
  ]},
  { moduleKey:'lisa', moduleLabel:'Lisa AI', moduleIcon:'ti-robot', features:[
    { key:'lisa.module.access', label:'Module zichtbaar' },
    { key:'lisa.conversation.view', label:'Conversaties bekijken' },
    { key:'lisa.conversation.takeover', label:'Conversatie overnemen' },
    { key:'lisa.conversation.intervene', label:'Bericht onderbreken' },
    { key:'lisa.conversation.status_update', label:'Conversatie-status wijzigen (qualified/disqualify/pauze)' },
    { key:'lisa.config.view', label:'Config bekijken' },
    { key:'lisa.config.edit', label:'Config bewerken (draft)' },
    { key:'lisa.config.publish', label:'Config publiceren (live zetten)' },
    { key:'lisa.sandbox.use', label:'Sandbox-chat gebruiken' },
    { key:'lisa.feedback.give', label:'Feedback geven op berichten' },
    { key:'lisa.kb.edit', label:'Lisa kennisbank bewerken' },
    { key:'lisa.stats.view', label:'Statistieken bekijken' },
    { key:'lisa.logs.view', label:'Logs &amp; versiegeschiedenis bekijken' },
  ]},
  { moduleKey:'controlcenter', moduleLabel:'Control Center', moduleIcon:'ti-target', features:[
    { key:'controlcenter.module.access', label:'Module zichtbaar' },
    { key:'controlcenter.kpi.view', label:'KPI bekijken' },
    { key:'controlcenter.approvals.view', label:'Approvals bekijken' },
    { key:'controlcenter.audit.view', label:'Audit log bekijken' },
    { key:'controlcenter.approval.act', label:'Approve/Reject' },
    { key:'controlcenter.audit.export', label:'Audit CSV export (gevoelig)' },
  ]},
  { moduleKey:'followup', moduleLabel:'Follow-up', moduleIcon:'ti-chart-line', features:[
    { key:'followup.module.access', label:'Module zichtbaar' },
    { key:'followup.tab.vandaag', label:'Tab: Vandaag' },
    { key:'followup.tab.openacties', label:'Tab: Open acties' },
    { key:'followup.tab.opvolging', label:'Tab: Opvolging' },
    { key:'followup.tab.archief', label:'Tab: Archief' },
    { key:'followup.tab.kalender', label:'Tab: Kalender' },
    { key:'followup.metrics.view', label:'Dashboard-metrics' },
    { key:'followup.overdue.view', label:'Overdue topbar' },
    { key:'followup.scope.all_vs_own', label:'Alle sales zien (vs eigen)' },
    { key:'followup.call.move', label:'Call verplaatsen' },
    { key:'followup.call.cancel', label:'Call annuleren' },
    { key:'followup.appointment.delete', label:'Appointment verwijderen' },
    { key:'followup.note.save', label:'Notitie opslaan' },
    { key:'followup.lead.view', label:'Lead detail bekijken' },
    { key:'followup.screenshot.upload', label:'Screenshot uploaden' },
    { key:'followup.lead.note', label:'Lead notitie' },
    { key:'followup.admin.module.access', label:'Admin-review module' },
    { key:'followup.audit.approve', label:'Audit goedkeuren' },
    { key:'followup.audit.reject', label:'Audit afkeuren' },
  ]},
  { moduleKey:'klanten', moduleLabel:'Klanten', moduleIcon:'ti-users-group', features:[
    { key:'customer.module.access', label:'Module zichtbaar' },
    { key:'customer.view', label:'Klant bekijken' },
    { key:'customer.create', label:'Klant aanmaken' },
    { key:'customer.edit', label:'Klant bewerken' },
    { key:'customer.archive', label:'Archiveren (soft delete)' },
    { key:'customer.hard_delete', label:'Permanent verwijderen' },
    { key:'customer.tag_manage', label:'Tags toekennen' },
    { key:'customer.tag_definitions_manage', label:'Tag-definities beheren' },
    { key:'customer.widget.sales.view', label:'Tab: Sales' },
    { key:'customer.widget.finance.view', label:'Tab: Finance' },
    { key:'customer.audit.view', label:'Tab: Audit' },
    { key:'customer.notes.write', label:'Notitie schrijven' },
    { key:'customer.notes.read', label:'Notitie lezen' },
    { key:'customer.avg.export', label:'AVG inzage-export' },
    { key:'customer.avg.anonymize', label:'AVG anonimiseren' },
  ]},
  { moduleKey:'ads', moduleLabel:'Meta Ads', moduleIcon:'ti-brand-meta', features:[
    // Fase 2 Meta Ads dashboard. Page-gate + endpoint-gate delen dezelfde key.
    // Fase 3 (alerts) haakt op ads.module.access voor de doelgroep van alerts.
    { key:'ads.module.access', label:'Dashboard zichtbaar' },
    // Fase 4 — Creative Studio (browser-compositor). Aparte permissie zodat
    // teams die alleen creatives maken geen dashboard-toegang nodig hebben.
    { key:'ads.studio.access', label:'Creative Studio' },
  ]},
  { moduleKey:'whatsapp', moduleLabel:'WhatsApp', moduleIcon:'ti-brand-whatsapp', features:[
    { key:'whatsapp.send_manual', label:'Handmatig WA sturen' },
    { key:'whatsapp.inbox.view', label:'Inbox bekijken' },
    { key:'whatsapp.inbox.view_all', label:'Hele inbox zien (vs eigen)' },
    { key:'whatsapp.numbers.manage', label:'Nummers beheren' },
    { key:'whatsapp.templates.view', label:'Templates bekijken' },
    { key:'whatsapp.templates.edit', label:'Templates bewerken' },
    { key:'whatsapp.templates.submit', label:'Indienen voor Meta-approval' },
  ]},
  { moduleKey:'brieven', moduleLabel:'Brieven', moduleIcon:'ti-mail-forward', features:[
    { key:'letter.generate', label:'Brief genereren' },
    { key:'letter.send_postnl', label:'Versturen via PostNL' },
  ]},
  { moduleKey:'sales', moduleLabel:'Sales-module', moduleIcon:'ti-shopping-cart', features:[
    { key:'sales.module.access', label:'Module zichtbaar' },
    { key:'sales.product.manage', label:'Productcatalogus beheren' },
    { key:'sales.product.view', label:'Productcatalogus bekijken' },
    { key:'sales.customer.create', label:'Klant aanmaken (sales-wizard)' },
    { key:'sales.customer.view', label:'Klant-overzicht bekijken' },
    { key:'sales.customer.tag_manage', label:'Klant-tags toevoegen' },
    { key:'sales.deal.create', label:'Offerte aanmaken' },
    { key:'sales.reservation_fee.bypass', label:'Reserveringsfee (€100) omzeilen bij abonnement-invoer' },
    { key:'leads.view',    label:'Leads-module bekijken' },
    { key:'leads.update',  label:'Leads bewerken (status/notitie/eigenaar)' },
    { key:'leads.promote', label:'Lead doorzetten naar klant' },
    { key:'leads.delete',  label:'Leads verwijderen/herstellen (archief)' },
    { key:'sales.deal.edit', label:'Offerte bewerken' },
    { key:'sales.deal.view', label:'Offerte bekijken' },
    { key:'sales.bonus.view_own', label:'Eigen bonus bekijken' },
    { key:'sales.dashboard.view', label:'Sales dashboard bekijken' },
    { key:'sales.retention.view', label:'Retentie-pipeline bekijken' },
    { key:'sales.first_call.view', label:'1e call ready widget' },
    { key:'sales.reports.view', label:'Rapporten + KPIs bekijken' },
  ]},
  { moduleKey:'salestabs', moduleLabel:'Sales-tabs', moduleIcon:'ti-layout-navbar', features:[
    { key:'sales.tab.dashboard',     label:'Tab: Dashboard' },
    { key:'sales.tab.customers',     label:'Tab: Klanten' },
    { key:'sales.tab.quotations',    label:'Tab: Offertes' },
    { key:'sales.tab.subscriptions', label:'Tab: Abonnementen' },
    { key:'sales.tab.retentie',      label:'Tab: Retentie' },
    { key:'sales.tab.aanbod',        label:'Tab: Aanbod' },
    { key:'sales.tab.reports',       label:'Tab: Rapporten' },
  ]},
  { moduleKey:'students', moduleLabel:'Studenten', moduleIcon:'ti-school', features:[
    { key:'students.all.view', label:'Alle studenten — overzicht' },
  ]},
  { moduleKey:'onboarding', moduleLabel:'Onboarding', moduleIcon:'ti-user-plus', features:[
    { key:'onboarding.admin',            label:'Onboarding-admin (ziet alles + student annuleren — onomkeerbaar)' },
    { key:'onboarding.assign_mentor',    label:'Student aan mentor (her)toewijzen — dropdown in overzicht' },
    { key:'onboarding.wizard.edit',     label:'Tab: Wizard (bewerken)' },
    { key:'onboarding.automation.view', label:'Tab: Automations' },
    { key:'onboarding.inbox.reply_link', label:'Reageren-knop in e-mailthread (link naar mailmodule)' },
    { key:'onboarding.inbox.view',       label:'Inbox: gesprekken bekijken' },
    { key:'onboarding.inbox.send',       label:'Inbox: berichten versturen' },
    { key:'onboarding.mila.use',         label:'"Vraag Mila"-suggesties in de inbox' },
  ]},
  { moduleKey:'finance', moduleLabel:'Finance', moduleIcon:'ti-currency-euro', features:[
    { key:'finance.module.access', label:'Module zichtbaar' },
    { key:'finance.customer.edit', label:'Klant bewerken (finance)' },
    { key:'finance.customer.view_full', label:'Klant volledig dossier (incl. bedragen)' },
    { key:'finance.customer.delete', label:'Klant verwijderen/archive' },
    { key:'finance.deal.pause', label:'Deal pauzeren (uitstel-regeling)' },
    { key:'finance.subscription.push', label:'Abonnement naar Teamleader pushen' },
    { key:'finance.subscription.view', label:'Abonnement bekijken' },
    { key:'finance.invoice.view', label:'Factuur bekijken' },
    { key:'finance.invoice.create_manual', label:'Handmatige factuur maken' },
    { key:'finance.invoice.push_to_tl', label:'Factuur naar Teamleader pushen' },
    { key:'finance.invoice.payment.register', label:'Betaling registreren / afletteren' },
    { key:'finance.invoice.payment.remove', label:'Betaling terugdraaien (alle betalingen)' },
    { key:'finance.invoice.send', label:'Factuur (her)verzenden' },
    { key:'finance.invoice.update', label:'Factuur aanpassen (concept)' },
    { key:'finance.invoice.credit', label:'Factuur crediteren (creditnota)' },
    { key:'finance.invoice.create', label:'Nieuwe factuur aanmaken' },
    { key:'finance.quote.view', label:'Offerte bekijken' },
    { key:'finance.bank.balance_view', label:'Banksaldo bekijken' },
    { key:'finance.bank.transactions_view', label:'Bank-transacties bekijken' },
    { key:'finance.bank.match_approve', label:'Match goedkeuren' },
    { key:'finance.bank.match_auto_toggle', label:'Auto-match aan/uit' },
    { key:'finance.bank.category_manage', label:'Categorieën beheren' },
    { key:'finance.expenses.view', label:'Uitgaven-analyse bekijken' },
    { key:'finance.expenses.category.edit', label:'Uitgaven categoriseren + PayPal uploaden' },
    { key:'finance.dunning.view', label:'Wanbetaler-trajecten bekijken' },
    { key:'finance.dunning.manage', label:'Wanbetaler-traject beheren' },
    { key:'finance.dunning.templates_edit', label:'Wanbetaler-templates bewerken' },
    { key:'finance.dunning.escalate_manual', label:'Handmatig escaleren' },
    { key:'finance.dunning.config', label:'Workflows + templates beheren' },
    { key:'finance.dunning.execute', label:'Workflow handmatig starten / pauzeren' },
    { key:'finance.arrangements.view', label:'Betalingsregelingen bekijken' },
    { key:'finance.arrangements.propose', label:'Betalingsregeling voorstellen' },
    { key:'finance.arrangements.approve', label:'Voorstellen goedkeuren/afwijzen' },
    { key:'finance.tasks.view', label:'Taken-dashboard bekijken' },
    { key:'finance.tasks.create', label:'Verify-payment task aanmaken' },
    { key:'finance.joost.view', label:'Joost suggesties zien' },
    { key:'finance.joost.use', label:'Joost suggesties gebruiken (verstuur namens jou)' },
    { key:'finance.joost.autonomy_pause', label:'Joost autonomy pauzeren / hervatten per conversatie' },
    { key:'finance.whatsapp.send_manual', label:'Finance-WhatsApp handmatig versturen' },
    { key:'finance.whatsapp.inbox_view', label:'Finance-WhatsApp inbox' },
    { key:'finance.whatsapp.numbers_manage', label:'Finance WhatsApp-nummers' },
    { key:'finance.inbox.view', label:'Inbox-tab zichtbaar (WhatsApp Cloud API)' },
    { key:'finance.inbox.send', label:'Bericht versturen vanuit Inbox (WhatsApp)' },
    { key:'finance.bonus.view_all', label:'Alle bonussen bekijken (manager-view)' },
    { key:'finance.bonus.config_manage', label:'Bonus-configs beheren' },
    { key:'finance.dashboard.executive_view', label:'Executive dashboard' },
    { key:'finance.reports.view', label:'Rapporten bekijken' },
    { key:'finance.reports.export', label:'Rapport exporteren' },
    { key:'finance.reports.distribution_manage', label:'Maandrapport-verzending beheren' },
    { key:'finance.forecast.view', label:'Forecast bekijken' },
    { key:'finance.forecast.scenarios_manage', label:"Forecast-scenario's beheren" },
    { key:'finance.settings.dunning_flow', label:'Wanbetaler-flow instellen' },
    { key:'finance.settings.alerts', label:'Alerts instellen' },
    { key:'finance.audit.view', label:'Finance-audit log bekijken' },
  ]},
  { moduleKey:'events', moduleLabel:'Events', moduleIcon:'ti-calendar-event', features:[
    { key:'events.module.access', label:'Module zichtbaar' },
    { key:'events.event.view', label:'Event bekijken' },
    { key:'events.event.create', label:'Event aanmaken' },
    { key:'events.event.edit', label:'Event bewerken' },
    { key:'events.event.delete', label:'Event verwijderen' },
    { key:'events.event.publish', label:'Event publiceren (concept -> live)' },
    { key:'events.event.cancel', label:'Event annuleren / archiveren' },
    { key:'events.event.complete', label:'Event afronden (F5.1: aanwezigheid + uitgaven + ledger)' },
    { key:'events.mentor.assign', label:'Mentoren koppelen aan event' },
    { key:'events.team_member.link', label:'Mentor/team-member koppelen aan gebruikersaccount (F5.0)' },
    { key:'events.attendee.view', label:'Deelnemer bekijken' },
    { key:'events.attendee.create', label:'Deelnemer toevoegen' },
    { key:'events.attendee.edit', label:'Deelnemer bewerken' },
    { key:'events.attendee.delete', label:'Deelnemer verwijderen' },
    { key:'events.attendee.status_change', label:'Status wijzigen (aanwezig / no-show / sale)' },
    { key:'events.attendee.tag_assign', label:'Tags toekennen aan deelnemer' },
    { key:'events.attendee.bulk_import', label:'Deelnemers bulk-importeren (CSV / deforexopleiding.nl / GHL)' },
    { key:'events.attendee.assessment_view', label:'Ingevulde vragenlijst inzien' },
    { key:'events.tag.manage_catalog', label:'Tags-catalogus beheren (gevoelig)' },
    { key:'events.inbox.view', label:'Events-inbox bekijken (WhatsApp Cloud API - events-lijn)' },
    { key:'events.inbox.reply_link', label:'Reageren-knop in e-mailthread (link naar mailmodule)' },
    { key:'events.simone.use', label:'Simone suggesties gebruiken (events-agent)' },
    { key:'events.audit.view', label:'Audit log per deelnemer bekijken' },
  ]},
  { moduleKey:'mentor', moduleLabel:'Mentor-grootboek', moduleIcon:'ti-book', features:[
    { key:'mentor.module.access', label:'Module zichtbaar (sidebar-link)' },
    { key:'mentor.ledger.view', label:'Grootboek bekijken (mentor: eigen rijen; manager+: alles)' },
    { key:'mentor.ledger.write', label:'Handmatig status van ledger-entries wijzigen' },
    { key:'mentor.payout.run', label:'Uitbetalings-run starten (vrijgegeven entries -> uitbetaald)' },
    { key:'mentor.admin.view', label:'Mentor admin-view (per mentor meekijken via /modules/mentor-detail.html)' },
  ]},
  { moduleKey:'admin', moduleLabel:'Admin', moduleIcon:'ti-settings', features:[
    { key:'admin.module.access', label:'Module zichtbaar' },
    { key:'admin.user.invite', label:'Gebruiker uitnodigen' },
    { key:'admin.user.role_change', label:'Rol wijzigen' },
    { key:'admin.user.deactivate', label:'Deactiveren' },
    { key:'admin.user.reactivate', label:'Reactiveren' },
    { key:'admin.invite.resend', label:'Uitnodiging herhalen' },
    { key:'admin.role.assign_super_admin', label:'super_admin toekennen (kritiek)' },
    { key:'admin.permissions.edit', label:'Rechten matrix bewerken (super only)' },
    { key:'admin.integrations.manage', label:"Integraties beheren (Teamleader-koppeling, etc.)" },
    { key:'admin.whatsapp_config', label:'WhatsApp Module Connections beheer' },
    { key:'admin.whatsapp_templates', label:'WhatsApp Templates beheer' },
    { key:'admin.arrangement_settings', label:'Auto-execute toggles configureren (D4)' },
    { key:'admin.joost_config', label:'Joost configuratie aanpassen' },
    { key:'admin.simone_config', label:'Simone configuratie aanpassen (events-agent)' },
    { key:'admin.joost_autonomy', label:'Joost autonomy-config + feature flags beheren' },
  ]},
  { moduleKey:'tickets', moduleLabel:'Tickets', moduleIcon:'ti-ticket', features:[
    { key:'tickets.module.access', label:'Module zichtbaar' },
    { key:'tickets.ticket.create', label:'Ticket aanmaken' },
    { key:'tickets.ticket.edit', label:'Ticket bewerken (eigen of admin)' },
    { key:'tickets.ticket.assign', label:'Ticket toewijzen (admin only)' },
    { key:'tickets.ticket.resolve', label:'Ticket sluiten (eigen of admin)' },
    { key:'tickets.ticket.delete', label:'Ticket verwijderen (admin only)' },
    { key:'tickets.comment.create', label:'Comment plaatsen' },
    { key:'tickets.admin.view_all', label:'Alle tickets zien (admin)' },
  ]},
  { moduleKey:'activity-log', moduleLabel:'Logboek', moduleIcon:'ti-history', features:[
    { key:'audit.log.view', label:'Logboek bekijken' },
  ]},
];

// super_admin = auto (impliciet alles, geen vinkjes). Overige rollen wel.
const RBAC_ROLES = [
  { key:'super_admin', label:'super_admin', auto:true },
  { key:'manager', label:'manager' },
  { key:'sales', label:'sales' },
  { key:'mentor', label:'mentor' },
  { key:'marketing', label:'marketing' },
  { key:'administratie', label:'administratie' },
];
  window.KV_RBAC = { FEATURE_REGISTRY, RBAC_ROLES };
})();
