-- ============================================================================
-- Migratie 014: RBAC role_permissions-seed voor role-based landing
-- Datum: 2026-06-26
-- Branch: feat/rbac-role-landing
--
-- DOEL: vastleggen van de role_permissions-grants die in PROD zijn gezet zodat
-- manager / sales / mentor na login op hun eigen dashboard kunnen landen en
-- de bijbehorende modules kunnen gebruiken. De grants zelf zijn al
-- productioneel actief (handmatig gedraaid op 26 juni 2026); dit bestand is
-- puur een geschiedenis-record voor versiebeheer.
--
-- Mapping (zie modules/shared/supabase-client.js → ROLE_LANDING):
--   super_admin → /index.html                       (bypass, geen rij nodig)
--   admin       → /index.html
--   manager     → /modules/control-center.html
--   sales       → /modules/sales-dashboard.html → /modules/sales.html?tab=dashboard
--   mentor      → /modules/mentor-dashboard.html
--   marketing / administratie / viewer → /index.html (geen extra grant nodig)
--
-- Inhoud: één big-INSERT met de exact-geseede 166 (role, feature_key, true)
-- rijen — manager 95 / sales 47 / mentor 24.
--
-- IDEMPOTENT (ON CONFLICT DO NOTHING): bij herhaald draaien worden bestaande
-- grants niet overschreven; ontbrekende worden alsnog toegevoegd. Tweak-safe:
-- handmatige aanpassingen aan losse rijen na deze migratie blijven behouden.
--
-- super_admin krijgt geen rij: user_has_permission() returnt true voor alles
-- bij super_admin via de explicit bypass in de RPC-helper (zie migratie 002).
-- ============================================================================

BEGIN;

INSERT INTO public.role_permissions (role, feature_key, allowed) VALUES
  ('manager','agents.module.access',true),
  ('manager','controlcenter.module.access',true),
  ('manager','customer.module.access',true),
  ('manager','dashboard.module.access',true),
  ('manager','email.heranalyseer.run',true),
  ('manager','email.module.access',true),
  ('manager','email.reclassify.run',true),
  ('manager','events.attendee.assessment_view',true),
  ('manager','events.attendee.create',true),
  ('manager','events.attendee.delete',true),
  ('manager','events.attendee.edit',true),
  ('manager','events.attendee.status_change',true),
  ('manager','events.attendee.tag_add',true),
  ('manager','events.attendee.tag_assign',true),
  ('manager','events.attendee.tag_remove',true),
  ('manager','events.attendee.view',true),
  ('manager','events.audit.view',true),
  ('manager','events.event.complete',true),
  ('manager','events.event.create',true),
  ('manager','events.event.delete',true),
  ('manager','events.event.edit',true),
  ('manager','events.event.publish',true),
  ('manager','events.event.view',true),
  ('manager','events.inbox.view',true),
  ('manager','events.mentor.assign',true),
  ('manager','events.mentor.remove',true),
  ('manager','events.module.access',true),
  ('manager','events.publish',true),
  ('manager','events.simone.use',true),
  ('manager','events.team_member.link',true),
  ('manager','finance.arrangements.approve',true),
  ('manager','finance.arrangements.propose',true),
  ('manager','finance.arrangements.view',true),
  ('manager','finance.bank.balance_view',true),
  ('manager','finance.bank.transactions_view',true),
  ('manager','finance.dunning.config',true),
  ('manager','finance.dunning.execute',true),
  ('manager','finance.dunning.view',true),
  ('manager','finance.inbox.send',true),
  ('manager','finance.inbox.view',true),
  ('manager','finance.invoice.create',true),
  ('manager','finance.invoice.credit',true),
  ('manager','finance.invoice.payment.register',true),
  ('manager','finance.invoice.payment.remove',true),
  ('manager','finance.invoice.send',true),
  ('manager','finance.invoice.update',true),
  ('manager','finance.invoice.view',true),
  ('manager','finance.joost.autonomy_pause',true),
  ('manager','finance.joost.use',true),
  ('manager','finance.module.access',true),
  ('manager','finance.subscription.push',true),
  ('manager','finance.tasks.create',true),
  ('manager','finance.tasks.view',true),
  ('manager','followup.module.access',true),
  ('manager','kennisbank.item.create',true),
  ('manager','kennisbank.item.delete',true),
  ('manager','kennisbank.item.edit',true),
  ('manager','kennisbank.module.access',true),
  ('manager','kennisbank.tag.manage',true),
  ('manager','lisa.config.edit',true),
  ('manager','lisa.config.publish',true),
  ('manager','lisa.config.view',true),
  ('manager','lisa.module.access',true),
  ('manager','lisa.sandbox.use',true),
  ('manager','meetings.module.access',true),
  ('manager','mentor.admin.view',true),
  ('manager','mentor.assessments.admin',true),
  ('manager','mentor.funded.admin',true),
  ('manager','mentor.ledger.view',true),
  ('manager','mentor.ledger.write',true),
  ('manager','mentor.module.access',true),
  ('manager','mentor.payout.manage',true),
  ('manager','mentor.payout.revert',true),
  ('manager','mentor.payout.run',true),
  ('manager','onboarding.admin',true),
  ('manager','onboarding.assign_mentor',true),
  ('manager','onboarding.automation.edit',true),
  ('manager','onboarding.automation.view',true),
  ('manager','onboarding.create',true),
  ('manager','onboarding.inbox.send',true),
  ('manager','onboarding.inbox.view',true),
  ('manager','onboarding.mila.use',true),
  ('manager','onboarding.wizard.edit',true),
  ('manager','sales.customer.create',true),
  ('manager','sales.customer.view',true),
  ('manager','sales.deal.create',true),
  ('manager','sales.deal.edit',true),
  ('manager','sales.deal.view',true),
  ('manager','sales.module.access',true),
  ('manager','sales.product.manage',true),
  ('manager','sales.product.view',true),
  ('manager','sales.reports.view',true),
  ('manager','taken.module.access',true),
  ('manager','tickets.module.access',true),
  ('manager','tickets.ticket.assign',true),
  ('sales','dashboard.module.access',true),
  ('sales','dashboard.sales.view',true),
  ('sales','sales.customer.create',true),
  ('sales','sales.customer.view',true),
  ('sales','sales.deal.create',true),
  ('sales','sales.deal.edit',true),
  ('sales','sales.deal.view',true),
  ('sales','sales.module.access',true),
  ('sales','sales.product.manage',true),
  ('sales','sales.product.view',true),
  ('sales','sales.reports.view',true),
  ('sales','finance.module.access',true),
  ('sales','finance.invoice.view',true),
  ('sales','finance.invoice.create',true),
  ('sales','finance.invoice.update',true),
  ('sales','finance.invoice.send',true),
  ('sales','finance.subscription.push',true),
  ('sales','events.attendee.assessment_view',true),
  ('sales','events.attendee.create',true),
  ('sales','events.attendee.delete',true),
  ('sales','events.attendee.edit',true),
  ('sales','events.attendee.status_change',true),
  ('sales','events.attendee.tag_add',true),
  ('sales','events.attendee.tag_assign',true),
  ('sales','events.attendee.tag_remove',true),
  ('sales','events.attendee.view',true),
  ('sales','events.audit.view',true),
  ('sales','events.event.complete',true),
  ('sales','events.event.create',true),
  ('sales','events.event.delete',true),
  ('sales','events.event.edit',true),
  ('sales','events.event.publish',true),
  ('sales','events.event.view',true),
  ('sales','events.inbox.view',true),
  ('sales','events.mentor.assign',true),
  ('sales','events.mentor.remove',true),
  ('sales','events.module.access',true),
  ('sales','events.publish',true),
  ('sales','events.simone.use',true),
  ('sales','events.team_member.link',true),
  ('sales','followup.module.access',true),
  ('sales','customer.module.access',true),
  ('sales','taken.module.access',true),
  ('sales','meetings.module.access',true),
  ('sales','kennisbank.module.access',true),
  ('sales','email.module.access',true),
  ('sales','tickets.module.access',true),
  ('mentor','dashboard.module.access',true),
  ('mentor','mentor.module.access',true),
  ('mentor','mentor.ledger.view',true),
  ('mentor','sales.module.access',true),
  ('mentor','sales.customer.view',true),
  ('mentor','sales.customer.create',true),
  ('mentor','sales.deal.view',true),
  ('mentor','sales.deal.create',true),
  ('mentor','sales.deal.edit',true),
  ('mentor','sales.product.view',true),
  ('mentor','events.module.access',true),
  ('mentor','events.event.view',true),
  ('mentor','events.attendee.view',true),
  ('mentor','events.attendee.create',true),
  ('mentor','events.attendee.edit',true),
  ('mentor','events.attendee.status_change',true),
  ('mentor','events.attendee.assessment_view',true),
  ('mentor','events.attendee.tag_add',true),
  ('mentor','events.attendee.tag_assign',true),
  ('mentor','events.attendee.tag_remove',true),
  ('mentor','events.inbox.view',true),
  ('mentor','kennisbank.module.access',true),
  ('mentor','taken.module.access',true),
  ('mentor','meetings.module.access',true),
  ('mentor','onboarding.view_own',true),
  ('mentor','onboarding.inbox.view',true),
  ('mentor','onboarding.inbox.send',true)
ON CONFLICT (role, feature_key) DO NOTHING;

COMMIT;

-- ── ROLLBACK ────────────────────────────────────────────────────────────────
-- Verwijdert exact dezelfde 166 rijen als de INSERT hierboven. Tuple-based
-- WHERE-clause zodat er geen onbedoelde keys-per-rol worden weggehaald die
-- na deze migratie nog handmatig zijn toegevoegd.
--
-- DELETE FROM public.role_permissions
-- WHERE (role, feature_key) IN (
--   ('manager','agents.module.access'),
--   ('manager','controlcenter.module.access'),
--   ('manager','customer.module.access'),
--   ('manager','dashboard.module.access'),
--   ('manager','email.heranalyseer.run'),
--   ('manager','email.module.access'),
--   ('manager','email.reclassify.run'),
--   ('manager','events.attendee.assessment_view'),
--   ('manager','events.attendee.create'),
--   ('manager','events.attendee.delete'),
--   ('manager','events.attendee.edit'),
--   ('manager','events.attendee.status_change'),
--   ('manager','events.attendee.tag_add'),
--   ('manager','events.attendee.tag_assign'),
--   ('manager','events.attendee.tag_remove'),
--   ('manager','events.attendee.view'),
--   ('manager','events.audit.view'),
--   ('manager','events.event.complete'),
--   ('manager','events.event.create'),
--   ('manager','events.event.delete'),
--   ('manager','events.event.edit'),
--   ('manager','events.event.publish'),
--   ('manager','events.event.view'),
--   ('manager','events.inbox.view'),
--   ('manager','events.mentor.assign'),
--   ('manager','events.mentor.remove'),
--   ('manager','events.module.access'),
--   ('manager','events.publish'),
--   ('manager','events.simone.use'),
--   ('manager','events.team_member.link'),
--   ('manager','finance.arrangements.approve'),
--   ('manager','finance.arrangements.propose'),
--   ('manager','finance.arrangements.view'),
--   ('manager','finance.bank.balance_view'),
--   ('manager','finance.bank.transactions_view'),
--   ('manager','finance.dunning.config'),
--   ('manager','finance.dunning.execute'),
--   ('manager','finance.dunning.view'),
--   ('manager','finance.inbox.send'),
--   ('manager','finance.inbox.view'),
--   ('manager','finance.invoice.create'),
--   ('manager','finance.invoice.credit'),
--   ('manager','finance.invoice.payment.register'),
--   ('manager','finance.invoice.payment.remove'),
--   ('manager','finance.invoice.send'),
--   ('manager','finance.invoice.update'),
--   ('manager','finance.invoice.view'),
--   ('manager','finance.joost.autonomy_pause'),
--   ('manager','finance.joost.use'),
--   ('manager','finance.module.access'),
--   ('manager','finance.subscription.push'),
--   ('manager','finance.tasks.create'),
--   ('manager','finance.tasks.view'),
--   ('manager','followup.module.access'),
--   ('manager','kennisbank.item.create'),
--   ('manager','kennisbank.item.delete'),
--   ('manager','kennisbank.item.edit'),
--   ('manager','kennisbank.module.access'),
--   ('manager','kennisbank.tag.manage'),
--   ('manager','lisa.config.edit'),
--   ('manager','lisa.config.publish'),
--   ('manager','lisa.config.view'),
--   ('manager','lisa.module.access'),
--   ('manager','lisa.sandbox.use'),
--   ('manager','meetings.module.access'),
--   ('manager','mentor.admin.view'),
--   ('manager','mentor.assessments.admin'),
--   ('manager','mentor.funded.admin'),
--   ('manager','mentor.ledger.view'),
--   ('manager','mentor.ledger.write'),
--   ('manager','mentor.module.access'),
--   ('manager','mentor.payout.manage'),
--   ('manager','mentor.payout.revert'),
--   ('manager','mentor.payout.run'),
--   ('manager','onboarding.admin'),
--   ('manager','onboarding.assign_mentor'),
--   ('manager','onboarding.automation.edit'),
--   ('manager','onboarding.automation.view'),
--   ('manager','onboarding.create'),
--   ('manager','onboarding.inbox.send'),
--   ('manager','onboarding.inbox.view'),
--   ('manager','onboarding.mila.use'),
--   ('manager','onboarding.wizard.edit'),
--   ('manager','sales.customer.create'),
--   ('manager','sales.customer.view'),
--   ('manager','sales.deal.create'),
--   ('manager','sales.deal.edit'),
--   ('manager','sales.deal.view'),
--   ('manager','sales.module.access'),
--   ('manager','sales.product.manage'),
--   ('manager','sales.product.view'),
--   ('manager','sales.reports.view'),
--   ('manager','taken.module.access'),
--   ('manager','tickets.module.access'),
--   ('manager','tickets.ticket.assign'),
--   ('sales','dashboard.module.access'),
--   ('sales','dashboard.sales.view'),
--   ('sales','sales.customer.create'),
--   ('sales','sales.customer.view'),
--   ('sales','sales.deal.create'),
--   ('sales','sales.deal.edit'),
--   ('sales','sales.deal.view'),
--   ('sales','sales.module.access'),
--   ('sales','sales.product.manage'),
--   ('sales','sales.product.view'),
--   ('sales','sales.reports.view'),
--   ('sales','finance.module.access'),
--   ('sales','finance.invoice.view'),
--   ('sales','finance.invoice.create'),
--   ('sales','finance.invoice.update'),
--   ('sales','finance.invoice.send'),
--   ('sales','finance.subscription.push'),
--   ('sales','events.attendee.assessment_view'),
--   ('sales','events.attendee.create'),
--   ('sales','events.attendee.delete'),
--   ('sales','events.attendee.edit'),
--   ('sales','events.attendee.status_change'),
--   ('sales','events.attendee.tag_add'),
--   ('sales','events.attendee.tag_assign'),
--   ('sales','events.attendee.tag_remove'),
--   ('sales','events.attendee.view'),
--   ('sales','events.audit.view'),
--   ('sales','events.event.complete'),
--   ('sales','events.event.create'),
--   ('sales','events.event.delete'),
--   ('sales','events.event.edit'),
--   ('sales','events.event.publish'),
--   ('sales','events.event.view'),
--   ('sales','events.inbox.view'),
--   ('sales','events.mentor.assign'),
--   ('sales','events.mentor.remove'),
--   ('sales','events.module.access'),
--   ('sales','events.publish'),
--   ('sales','events.simone.use'),
--   ('sales','events.team_member.link'),
--   ('sales','followup.module.access'),
--   ('sales','customer.module.access'),
--   ('sales','taken.module.access'),
--   ('sales','meetings.module.access'),
--   ('sales','kennisbank.module.access'),
--   ('sales','email.module.access'),
--   ('sales','tickets.module.access'),
--   ('mentor','dashboard.module.access'),
--   ('mentor','mentor.module.access'),
--   ('mentor','mentor.ledger.view'),
--   ('mentor','sales.module.access'),
--   ('mentor','sales.customer.view'),
--   ('mentor','sales.customer.create'),
--   ('mentor','sales.deal.view'),
--   ('mentor','sales.deal.create'),
--   ('mentor','sales.deal.edit'),
--   ('mentor','sales.product.view'),
--   ('mentor','events.module.access'),
--   ('mentor','events.event.view'),
--   ('mentor','events.attendee.view'),
--   ('mentor','events.attendee.create'),
--   ('mentor','events.attendee.edit'),
--   ('mentor','events.attendee.status_change'),
--   ('mentor','events.attendee.assessment_view'),
--   ('mentor','events.attendee.tag_add'),
--   ('mentor','events.attendee.tag_assign'),
--   ('mentor','events.attendee.tag_remove'),
--   ('mentor','events.inbox.view'),
--   ('mentor','kennisbank.module.access'),
--   ('mentor','taken.module.access'),
--   ('mentor','meetings.module.access'),
--   ('mentor','onboarding.view_own'),
--   ('mentor','onboarding.inbox.view'),
--   ('mentor','onboarding.inbox.send')
-- );
